USE SchoolDatabase

CREATE TABLE TEST3(
NAME VARCHAR(20),
SSN	 CHAR(9),
DEPT_NUMBER INTEGER,
ACC_BALANCE SMALLMONEY
)

--Q11-1) TEST TABLE ON VARIES TYPES OF DATA IF IT ACCEPTING OR NOT

-- CHECKING THE ATTRIBUTES VALUES ARRANGEMENT
--1a)ACCEPTED
INSERT INTO TEST3
VALUES('ALI','234',1234,53)
--1b) NOT ACCEPTED, ERRO IN NAME=VALUE

INSERT INTO TEST3
VALUES(NAME='ZUBAIR',SSN='54',ACC_BALANCE=456,DEPT_NUMBER=342)

--1c) AGAIN ERROR
INSERT INTO TEST3(NAME,ACC_BALANCE,SSN,DEPT_NUMBER)
VALUES(NAME='ZUBAIR',SSN='54',ACC_BALANCE=456,DEPT_NUMBER=342)

--1d) ACCEPTED, THE SOLUTION OF 1B)
INSERT INTO TEST3(NAME,ACC_BALANCE,SSN,DEPT_NUMBER)
VALUES('ZUBAIR',456,'54',342)

--CHECKING THE DATATYPES ACCEPTANCE VALUES WITH DIFFERENT TYPES VALUES
--1e)CHECKING BY PUTING THE decimal values in integer data type
--accepted
INSERT INTO TEST3
VALUES('Azhar','yy',54.00,432)

--not accepted,OVERFLOW 
--1f) checking by the high range of int value greater then the smallmoney
INSERT INTO TEST3
VALUES('AHMED','3YY',546.00,765555555555)

--NOT ACCEPTED, INT AGAIN OVERFLOW
--1g) checking by the high range of decimal value in the int datatype
INSERT INTO TEST3
VALUES('YESIR','4YY34',547893487665.9887,76456)

--ACCEPTED 
INSERT INTO TEST3
VALUES('YOUNAS','76DDD',564456878.9877,6454)

--Q11-2a)CREATE AN INDEX OF SSN IN ASCENDING  ORDER OF SSN ATTRIBUTE,TRY INSERT NEW DATA INTO SSN
--CHECK SSN TAKES NULL VALUES
CREATE INDEX ASS_INDEX
ON TEST3(SSN)  --ASCENDING BY DEFAULT

--NOW TRYING TO PUT SOME NEW DATA TILL NOW DATA IS NOT NULL
--DATA ACCEPTED
INSERT INTO TEST3
VALUES('THANVEER','6544YY',4533,98)

--NOW TRYING TO PUT DUPLICATE VALUES IN SSN ATTRIBUTE, MADE AS INDEX
INSERT INTO TEST3
VALUES('THANVEER','5647Y',4556,98)

--ACCETPED
--NOW TRYING TO PUT EMPITY STRING BUT NOT NULL VALUE IN SSN ATTRITBUTE,
INSERT INTO TEST3
VALUES('','Y343',355,54)

--ACCEPTED
--NOW TRYING TO PUT NULL VALUE IN SSN ATTRIBUTE
INSERT INTO TEST3
VALUES(NULL,'Y343',554,55)

--CHECKING TABLE
SELECT *
FROM	TEST3


--NOW CREATING
--NOT POSSIBLE AS THE SSN ATTRIBUTE ALREADY HAS DUPLICATE VALUES
CREATE UNIQUE INDEX SSN_INDEX1
ON TEST3(SSN)
/*
--REMOVING THE DUPLICATE VALUES, as well as values empity string, which are not allowing unique index
update TEST3
SET SSN = 'RANA'
WHERE SSN LIKE 'Y%
*/

--TO MAKE A COLUMN NOT NULL, FIRST DELETE ALL INDEXES THAT ARE ATTACH TO THAT COLUMN
DROP INDEX TEST3.SSN_INDEX1
DROP INDEX TEST3.ASS_INDEX
--NOW MAKE IT NOT NULL
ALTER TABLE TEST3
ALTER COLUMN SSN CHAR(9) NOT NULL



--