use SchoolDatabase

--1) FIND THE NAMES OF THE STUDENTS WHO HAD 'HERMANO' INSTRUCTOR AND EARNED A GRADE 'B'OR BETTER IN CLASS
--CREATING INNER QUERY FIRST
CREATE VIEW SECTION_GRADE_VIEW AS
SELECT	SE.INSTRUCTOR AS [INSTUCTOR], GR.GRADE,GR.STUDENT_NUMBER  
FROM	SECTION SE INNER JOIN Grade_report GR
ON		SE.SECTION_ID = GR.SECTION_ID
WHERE	SE.INSTRUCTOR LIKE 'HERMANO'


--COMPLETE QUERY CREATION 
SELECT	S.SNAME AS [STUDENT NAMES],SGV.GRADE,SGV.INSTUCTOR
FROM	STUDENT S INNER JOIN SECTION_GRADE_VIEW SGV
ON		S.STNO = SGV.STUDENT_NUMBER
WHERE	SGV.GRADE = 'B'

--2) CREATE DUPLICATE TABLE OF STUDENT TABLE NAMES 'STUTAB'
SELECT * INTO #stutab
FROM	STUDENT S

--2A) LIST STUDENT NAMES  AND MAJORS OF THE JUNIORS AND SENIORS
SELECT  SNAME AS [STUDENT NAMES]
FROM	#stutab

--2B) STUDENT NAMES OF THE 'COSC' MAJOR
SELECT	SNAME AS [STUDENT NAMES]
FROM	#stutab
WHERE	MAJOR  = 'COSC'

--2C) CREATE A VIEW(CALL IT VSTV) THAT CONTAINS THE STUDENT NAMES AND MAJOR AS 'COSC'
CREATE VIEW VSTV AS
SELECT SNAME AS [STUDENT NAMES], MAJOR 
FROM	Student 
WHERE	MAJOR  =  'COSC'

--2D) LIST THE STUDENT NAMES and major as discending ORDER USING VIEW VSTV
SELECT	V.[STUDENT NAMES],V.MAJOR
FROM	VSTV  AS V
ORDER BY V.[STUDENT NAMES] DESC

--2E) MODIFY A ROW IN VSTV TABLE THAT A STUDENT CAN CHANGE HIS ROW 
UPDATE VSTV 
SET [STUDENT NAMES]= 'Zelda Z.'
WHERE [STUDENT NAMES] = 'Zelda'

--2F) YES THE MODIFICATION THROUGH VIEW ALSO EFFECT THE STUDENT TABLE
--2G) TRY TO MODIFY THE VIEW  AGAIN, BUT THIS TIME CHANGE  THE MAJOR TO COMPSC,
--ANSER NOT POSSIBLE BECAUSE THE DATATYPE LEN ALLOWED 4 CHARACTERS

UPDATE VSTV
SET MAJOR = 'COMPSC'

--2I) CREATE LOCAL TABLE #stutemp THAT  WORKS AS ABOVE QUERIES SECTION TWO VIEW QUERY, ALSO CHECK IF MODIFICATION REFLECTS IN 
--IN STUDENT TABLE TOO.
SELECT  SNAME AS [STUDENT NAME],MAJOR INTO #stutemp
FROM	Student
WHERE	MAJOR = 'COSC'

--UPDATE CHECKING
UPDATE  #stutemp
SET	   [STUDENT NAME] = 'Zaaldi'
WHERE  [STUDENT NAME] = 'Zelda Z.'

SELECT *
FROM	#stutemp

--NOT EFFECT BY UPDATE IN LOCAL TABLE
SElECT *
FROM Student
WHERE MAJOR= 'COSC'

--SAME AS IN VIEW IT COULD NOT
UPDATE #stutemp
SET	 MAJOR = 'COMPSC'

--3) IDENTIFY PRECIDENCE ISSUES, IT RUNS THE AND PART FIRST, TO REMOVE CONFUSION PUT PARENTHECIS
SELECT *
FROM Student
WHERE (stno < 100 AND major = 'COSC') OR major = 'ACCT'

SELECT *
FROM Student
WHERE stno < 100 AND( major = 'COSC' OR major = 'ACCT')

--4) FIND THE INSTRUCTOR NAME AND COURSE NAME FOR COMPUTER SCIENCE COURSE
--CONVERT INTO VIEW
CREATE VIEW SECTION_COURSE_VIEW AS
SELECT  SE.INSTRUCTOR , C.COURSE_NAME 
FROM	Section SE INNER JOIN Course C
ON		C.COURSE_NUMBER = SE.COURSE_NUM
WHERE	C.OFFERING_DEPT = 'COSC'

SELECT *
FROM	SECTION_COURSE_VIEW

--4B-C) CONVERT QUERY INTO AN INLINE QUERY WITH COLUMN ALIASES
SELECT  SE.INSTRUCTOR [INSTRUCTOR], C.COURSE_NAME [COURSE NAME]
FROM  SECTION SE,(SELECT    COURSE_NAME ,COURSE_NUMBER
				  FROM		Course 
				  WHERE		OFFERING_DEPT = 'COSC') AS C
WHERE	C.COURSE_NUMBER = SE.COURSE_NUM
ORDER BY  SE.INSTRUCTOR




	



