USE SchoolDatabase

--4) display courses names for all of the prerequest course
SELECT	C.COURSE_NAME AS [COURSES NAMES WITH PREREQUESTS] --P.PREREQ
FROM	Course C JOIN Prereq P
ON		C.COURSE_NUMBER = P.COURSE_NUMBER

--5a) display the course names,instructors,smester and years they were teaching
SELECT	C.COURSE_NAME 'COURSE NAME',S.INSTRUCTOR,S.SEMESTER,'20'+S.YEAR 'TEACHING YEAR'
FROM	Course C INNER JOIN Section S
ON		C.COURSE_NUMBER=S.COURSE_NUM

--5b) list the instructor, course names,departement of each course the instructor were teaching
SELECT	S.INSTRUCTOR,C.COURSE_NAME,D.DCODE [DEPARTEMENT OF COURSE INTSTRUCTOR]
FROM	Department_to_major D JOIN
		(Course C INNER JOIN Section S
		ON C.COURSE_NUMBER=S.COURSE_NUM)
 ON C.OFFERING_DEPT=D.DCODE

 --6a)  USE LIFT OUTER JOIN,list the course names, the instructor, the semester the year they were teaching, order by instructor descending 
 SELECT		C.COURSE_NAME,S.INSTRUCTOR,S.SEMESTER,'20'+S.YEAR AS [YEAR OF TEACHING]
 FROM		Course C LEFT OUTER JOIN Section S
 ON			C.COURSE_NUMBER =S.COURSE_NUM

 --6b) list the instructor ,course names,and departement of each  course the instructor were teaching
 SELECT		S.INSTRUCTOR, C.COURSE_NAME, D.DCODE AS [THE COURSE INSTRUCTOR DEPARTEMENT]
 FROM		Department_to_major D LEFT OUTER JOIN
			(COURSE C LEFT OUTER JOIN Section S
			 ON  C.COURSE_NUMBER = S.COURSE_NUM)
ON D.DCODE = C.OFFERING_DEPT

--7A) USE THE RIGHT OUTER JOIN,LIST THE INSTRUCTOR, THE COURSE NAME THE INSTRUCTOR TEACH AND THE YEAR AND SEMESTER 
SELECT	S.INSTRUCTOR,C.COURSE_NAME,S.SEMESTER, '20'+S.YEAR [TEACHING YEAR]
FROM	Course C RIGHT OUTER JOIN Section S
ON		C.COURSE_NUMBER = S.COURSE_NUM

--7B) FOR EACH COURSE , LIST THE NAME THE INSTRUCTOR, THE DEPARTEMENT NAME OF DEPARTEMENT THAT OFFER THE COURSE
SELECT	 C.COURSE_NAME,S.INSTRUCTOR,D.DCODE [COURSE DEPARTEMENT]
FROM	(Course C RIGHT OUTER JOIN Section S 
		ON C.COURSE_NUMBER=S.COURSE_NUM)
RIGHT OUTER JOIN Department_to_major D
ON	C.OFFERING_DEPT=D.DCODE

--8B) USE FULL OUTER JOIN,FOR 7B)
SELECT	 C.COURSE_NAME,S.INSTRUCTOR,D.DCODE [COURSE DEPARTEMENT]
FROM	(Course C FULL OUTER JOIN Section S 
		ON C.COURSE_NUMBER=S.COURSE_NUM)
FULL  OUTER JOIN Department_to_major D
ON	C.OFFERING_DEPT=D.DCODE

SELECT	 C.COURSE_NAME,S.INSTRUCTOR,D.DCODE [COURSE DEPARTEMENT]
FROM	 Department_to_major D 	FULL  OUTER JOIN
		(Course C FULL OUTER JOIN Section S 
		ON C.COURSE_NUMBER=S.COURSE_NUM)
ON	C.OFFERING_DEPT=D.DCODE
WHERE C.OFFERING_DEPT IS NOT NULL

--9) DATA OPPOSIT TO INNER JOIN 
SELECT *
FROM Course AS c, Prereq AS p
WHERE c.COURSE_NUMBER<>P.COURSE_NUMBER

--10) ALL THOSE STUDENTS THAT ARE MORE SENIOR THEN OUTHERS
SELECT	*
FROM	Student S1,Student S2
WHERE   S1.CLASS>S2.CLASS
AND		S2.CLASS>=3

--12)  Display a list of the names of all students who have dependents, and the
--dependent’s name, relationship, and age, ordered by age of dependent.
SELECT	 S.SNAME [STUDENT NAMES],D.DNAME [DEPENDENT NAME],D.AGE [DEPENDENT AGE]
FROM	Student S INNER JOIN Dependent D
ON		S.STNO =D.PNO 
WHERE	D.AGE IS NOT NULL

SELECT	 S.SNAME [STUDENT NAMES],D.DNAME [DEPENDENT NAME],D.AGE [DEPENDENT AGE]
FROM	Student S,Dependent D
WHERE	S.STNO =D.PNO 
AND 	D.AGE IS NOT NULL



		
